"""weatherdb

Revision ID: fb907be98dca
Revises: 
Create Date: 2018-01-16 08:20:13.542614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb907be98dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_report',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id_log')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_report')
    # ### end Alembic commands ###
